apiVersion: v1
kind: Pod
metadata:
  name: team-pod
  labels:
    name: team-pod
spec:
  containers:
  - name: team-pod
    image: busybox
    command: ["sleep", "4800"]
    envFrom:
    - configMapRef:
        name: users-cm
    resources:
      limits:
        memory: "64Mi"
        cpu: "100m"
    