apiVersion: v1
kind: Pod
metadata:
  name: team-volume-pod 
  labels:
    name: team-volume-pod 
spec:
  volumes:
    - name: team-volume
      configMap:
        name: users-cm
  containers:
  - name: team-volume-pod
    image: busybox
    command: ["sleep", "3600"]
    volumeMounts:
      - name: team-volume
        mountPath: /data/team-members
    resources:
      limits:
        memory: "64Mi"
        cpu: "100m"
    