apiVersion: v1
kind: Pod
metadata:
  name: email-pod
  labels:
    name: email-pod
spec:
  containers:
  - name: email-pod
    image: busybox
    command: ["sleep", "4800"]
    env:
      - name: EMAIL
        valueFrom:
          secretKeyRef:
            key: email
            name: devops-secret
    resources:
      limits:
        memory: "64Mi"
        cpu: "100m"

