apiVersion: v1
kind: Pod
metadata:
  name: dev-pod
  labels:
    name: dev-pod
spec:
  containers:
  - name: dev-pod
    image: busybox
    command: ["sleep", "4800"]
    envFrom:
      - secretRef:
          name: devops-secret
    resources:
      limits:
        memory: "64Mi"
        cpu: "100m"

