apiVersion: v1
kind: Pod
metadata:
  name: dev-volume-pod
spec:
  containers:
  - name: dev-volume-pod
    image: busybox
    command:
      - "sleep"
      - "3600"
    volumeMounts:
    - name: devops-volume
      mountPath: "/data/devops-secret"
    resources:
      limits:
        memory: "64Mi"
        cpu: "10"    
  volumes:
  - name: devops-volume
    secret:
      secretName: devops-secret