apiVersion: v1
kind: Pod
metadata:
  labels:
    run: redis
  name: redis
spec:
  containers:
  - image: redis:5.0.6-alpine3.10
    name: redis
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  restartPolicy: Always
