apiVersion: v1
kind: Pod
metadata:
  name: i-know-who-i-am
  namespace: default
  labels:
    name: i-know-who-i-am
spec:
  containers:
  - name: i-know-who-i-am
    image: busybox:latest
    env:
      - name: POD_NODE
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: POD_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace     
    resources:
      limits:
        memory: "64Mi"
        cpu: "100m"

    command: [ "/bin/sh", "-c"]
    args: 
    - |
      printenv
      sleep infinity