apiVersion: v1
kind: Namespace
metadata:
  name: tomato

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tomato
  labels:
    vegetable: tomato
  name: tomato
spec:
  replicas: 3
  selector:
    matchLabels:
      vegetable: tomato
  template:
    metadata:
      labels:
        vegetable: tomato
    spec:
      containers:
      - name: tomato
        image: nginx:1.16-alpine
        resources:
          limits:
            memory: "64Mi"
            cpu: "100m"
        ports:
          - containerPort: 80

