apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJd01UQXdPVEU1TkRjd04xb1hEVE13TVRBd056RTVORGN3TjFvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTE9JCjdWbnRaOWRqK2ExTkZka2hLWHVvMzBiSWlxV0VDd3F3U25ib1AyamNBd0FDaGF6N0pQNEJvSGpqeEowd3dBODEKM0F0M01sUVJHS3kvYzBFTEYxWUppTVV5ME8zbk0vWHBhcWtpVHFiRFR2ZC93RjRndEpWbTJkV005YnZNanRCOApQdVlaS3ZVUWRheTZRRTdpRUlER0JqWU03SWVvVFpPZHRacmVWUzJJMkRmRnRsSThUa0VSMUFDVkZWQ3VWMTF3CmtNYVVseTdhYmZncVFUdlgzNWRPaWtpOEtzUWovZU9QeDMzNzRHMytFQTdoQzVWZ1RDQVZCZ1RoajVjL3FQL1UKWEYxbk95QkRQdStXdVR0dGw0Y2Z0TGw3bjBwMGVPYmoyeWFnSU1NUnJYZXdHNGlQVHAyNVJ3c1hteVNad1J2QgppWFRPeEpMdmhzdXFocmJraTNrQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZQQk9BS1h3Z1E4bmlyRjJ2TFl4NzRPQmk4WGJNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFBSXl0bGVoZjB0QnFGaldQcVlwZ1E3MVk0WnlNc1psRHFTVWtOY2pJOEREWUpSSjJ4YQo2SU9VVGp6SG5lQ3M5R0l6NitUaXNrVHkwQUZ6K2U5QXVPTW02VGF0Qk0ya0xTYnY0NlFjQkdsY1VsSmg3NmFiCjJsY3hqOE1MdEZKYjFwUndyM3QzRlB4ZzFsN1p1ZzA3UGlFb3pWTVltZThtSDlWU25iVGlQaFNYR25vaXZBQmIKSitrcmV4eUdLSnlaTkU5VzFKcUw2bVFnWjNRNXIzek9jRXhFSzdTdEZTSktmcnNJL1F6bDZuQS9IRDFiaGxxbAo4THRuUEZTeExQSFFBd3ZmbjBNUVlNVWowR0hsYXJWd3FueHdsNWhDc09MN1Z4SG5lY054TTJmS2o2VFkyVENxCnBiVGFFa3FlTll4SEc3MlRlQlI4dml5djhMVHhRdHpiUWRyUAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://api.k8slab.playpit.net:6443
  name: bootstrap
contexts:
- context:
    cluster: bootstrap
    user: kubelet-bootstrap
  name: bootstrap
current-context: bootstrap
kind: Config
preferences: {}
users:
- name: kubelet-bootstrap
  user:
    token: 07401b.f395accd246ae52d