apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicasCount }}
  selector:
    matchLabels:
      run: {{ .Release.Name }}
  template:
    metadata:
      labels:
        run: {{ .Release.Name }}
    spec:
      containers:
      - image: tomcat:{{ .Values.tomcatVersion }}
        name: {{ .Release.Name }}
        ports:
        - containerPort: 8080