apiVersion: v1
kind: Pod
metadata:
  name: emptydirvol
  labels:
    name: emptydirvol
spec:
  initContainers:
  - name: first-cont
    image: busybox
    command: ["wget", "-O"]
    args:
      - /webapps/ROOT/index.jsp
      - https://playpit-labs-assets.s3-eu-west-1.amazonaws.com/tomcat/index.jsp
    volumeMounts:
    - mountPath: /webapps/ROOT/
      name: shared-pod-volume
  containers:
  - name: second-cont
    image: tomcat:9.0-jre8-alpine
    resources:
      limits:
        memory: "64Mi"
        cpu: "100m"
    ports:
      - containerPort: 8080
    volumeMounts:
    - mountPath: /usr/local/tomcat/webapps/ROOT
      name: shared-pod-volume

  volumes:    
    - name: shared-pod-volume
      emptyDir: {}
