apiVersion: v1
kind: Pod
metadata:
  name: web-tricky-pod-emptydir
  labels:
    name: web-tricky-pod-emptydir
spec:
  initContainers:
  - name: first-cont
    image: busybox
    env:
    - name: POD_NODE
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    command: ["sh", "-c"]
    args:
      - 'echo -e "Student: Aliaksandr Dakutovich \n$POD_NODE \n$POD_IP" > /tmp/indexpage/index.html'
    volumeMounts:
    - mountPath: /tmp/indexpage
      name: shared-pod-volume
  containers:
  - name: second-cont
    image: nginx:1.17-alpine
    resources:
      limits:
        memory: "64Mi"
        cpu: "100m"
    ports:
      - containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: shared-pod-volume

  volumes:
    - name: shared-pod-volume
      emptyDir: {}