apiVersion: v1
kind: Service
metadata:
  name: web-tricky-pod-emptydir-svc
spec:
  type: NodePort
  selector:
    name: web-tricky-pod-emptydir
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30081
  
