apiVersion: v1
kind: Pod
metadata:
  name: web-pod-emptydir-tmpfs
  labels:
    name: web-pod-emptydir-tmpfs
spec:
  initContainers:
  - name: first-cont
    image: busybox
    command: ["sh", "-c"]
    args:
      - 'echo "initialized by initContainer, using tmpfs" > /html/index.html'
    volumeMounts:
    - mountPath: /html
      name: shared-pod-volume
  containers:
  - name: second-cont
    image: nginx:1.17-alpine
    resources:
      limits:
        memory: "64Mi"
        cpu: "100m"
    ports:
      - containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: shared-pod-volume

  volumes:
    - name: shared-pod-volume
      emptyDir:
        medium: Memory