apiVersion: v1
kind: Service
metadata:
  name: web-pod-emptydir-tmpfs
spec:
  type: NodePort
  selector:
    name: web-pod-emptydir-tmpfs
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30082
  
