apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adakutovich-data-pv-claim
spec:
  resources:
    requests:
      storage: 200Mi
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
