apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-with-sc
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: playpit-labs-storage