apiVersion: v1
kind: Pod
metadata:
  name: testing-pvc-sc
  labels:
    name: testing-pvc-sc
spec:
  containers:
  - name: testing-pvc-sc
    image: busybox
    command: ["sleep", "infinity"]
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
      - mountPath: /data
        name: customstorage
  volumes:
  - name: customstorage
    persistentVolumeClaim:
      claimName: pvc-with-sc
