apiVersion: v1
kind: Service
metadata:
  name: pod-info-nodeport-30080-svc
spec:
  ports:
  - nodePort: 30080
    port: 30080
    protocol: TCP
    targetPort: 80
  selector:
    app: pod-info
  type: NodePort