apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
rules:
- apiGroups: [""] 
  resources: ["pods"]
  verbs: ["list", "get"]
- apiGroups: ["apps"] 
  resources: ["deployments"]
  verbs: ["list", "get"]