apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: color-{{ .Values.color }}
  name: color-{{ .Values.color }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: color-{{ .Values.color }}
  template:
    metadata:
      labels:
        app: color-{{ .Values.color }}
    spec:
      containers:
      - image: {{ .Values.image }}
        name: color
        env:
        - name: COLOR
          value: {{ .Values.color }}


---

# color: green
# replicas: 1
# image: sbeliakou/color
# {{ .Values.replicasCount }}
---
apiVersion: v1
kind: Service
metadata:
  name: color-{{ .Values.color }}
spec:
  selector:
    app: color-{{ .Values.color }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: ClusterIP

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: color-{{ .Values.color }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: {{ .Values.color }}.k8slab.playpit.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: color-{{ .Values.color }}
            port:
              number: 8080